### ISSUE TITLE
Typo in the example

### ISSUE THREAD

**Issue by sompylasar** [amcss/attribute-module-specification#26]
The line

`[am-traitName~="three"], .breakpoint-mobile [am-traitName~="breakpoint:three"] { /* styles */ }`

should be

`[am-traitName~="three"], .breakpoint-mobile [am-traitName~="mobile:three"] { /* styles */ }`

(replace `breakpoint:three` with `mobile:three`).

**Comment by benschwarz** [comment]
@sompylasar Any chance you could turn this into a pull request?

**Comment by sompylasar** [comment]
No time to fork/edit/push. The repo owner will likely do this in a minute.

**Comment by kevinpeno** [comment]
@sompylasar You know you can make a PR by editing a file on the owner's repo right? No need to fork in the traditional sense. :)

**Comment by sompylasar** [comment]
@kevinpeno sorry I forgot about that feature, thanks for reminder.
