### ISSUE TITLE
What about attribute selectors efficiency

### ISSUE THREAD

**Issue by aantipov** [amcss/attribute-module-specification#27]
Hi guys
So the proposed approach is to use attribute selectors.
But I'm just wondering how efficient they are?
The following article from Mozilla says that attribute selectors are in a group of slowest selectors:
https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Writing_efficient_CSS

I know that the article is a little bit outdated but I couldn't find more up-to-date information on attribute selectors performance.

What do you think?

**Comment by curtisblackwell** [comment]
See #7

**Comment by aantipov** [comment]
Thanks @curtisblackwell !

**Comment by curtisblackwell** [comment]
:goat:
